variables:
  sut_ip: "10.99.104.251"
  reference: "test.msg"
  deploy_work: "/tmp/deploy"
  exe_path: "/tmp/deploy/$CI_PROJECT_NAME"
  script_cmd: "'ansible-playbook -i inventory --syntax-check *.yaml -vvv'"

.normal: &normal
  before_script:
    - chmod a+x *.sh *.py || true
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
  after_script:
    - docker logout
  tags:
    - IPT-K8S-NODE2

.tool: &tool
  before_script:
    - apk add --update curl git && rm -rf /var/cache/apk/*
    - git clone $TOOLS_PROJECT
  tags:
    - TA-SLAVE-RUNNER

stages:
  - lintcheck
  - checkyaml
  - cleanup

shellcheck:
  <<: *normal
  stage: lintcheck
  image: registry.ipt-gitlab:8081/sit-develop-tool/shellcheck:$SHCHECK_VER
  before_script:
    - echo "======>>>>>>>> shell script code styles check start."
  script:
    - find . -iname "*.sh" | xargs  shellcheck -s bash --color=always || true
  after_script:
    - echo "======>>>>>>>> shell script code styles check end."
  tags:
    - IPT-K8S-NODE2
  when: always

yamlsyntax:
  <<: *normal
  stage: checkyaml
  image: registry.ipt-gitlab:8081/sit-develop-tool/tool-ansible:$ANSIBLE_VER
  before_script:
    - |
        export VERSION=$(egrep -o 'Rev\:\ ([0-9].){2}[0-9]+' README.md | awk '{print $NF}')
        # print variables
        more << EOF
        Show Group variables:
        ===========================================================================
        EXE_PATH: $exe_path
        WORK_PATH: $deploy_work
        SUT_IP: $sut_ip
        SSH_PORT: $SSH_PORT
        VERSION: $VERSION
        ===========================================================================
        EOF

        # configure inventory (replace ";" to "\n")
        sed -i "s,<SRV_USER>,${SRV_USER},g" $PWD/inventory
        sed -i "s,<SRV_PASS>,${SRV_PASS},g" $PWD/inventory
        sed -i "s,<SRV_IP>,${sut_ip},g" $PWD/inventory
        sed -i "s,<PORT>,${SSH_PORT},g" $PWD/inventory
        sed -i -E "s,\;,\n,g" $PWD/inventory

        # deploy tools
        ansible "*" -i $PWD/inventory -m shell -a "echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin" -b
        ansible "*" -i $PWD/inventory -m shell -a "mkdir -p $deploy_work" -b
        ansible "*" -i $PWD/inventory -m copy  -a "src=$PWD dest=$deploy_work owner=$SRV_USER group=$SRV_USER" -b
        ansible "*" -i $PWD/inventory -m shell -a "cd $exe_path && chmod +x *.sh" || true
  script:
    - ansible "*" -i $PWD/inventory -m shell -a "cd $exe_path && bash -c ${script_cmd}" -b
  after_script:
    - |
        if [ -f ${PWD}/hosts ]; then
            export host_conf=hosts
        else
            export host_conf=inventory
        fi
        # generate artifacts in each host
        for e in $(grep -E '^([0-9]{1,3}\.){3}[0-9]{1,3}$' $host_conf)
        do
            ansible "*" -i ${PWD}/$host_conf -m shell -a "cd $exe_path && tar zcvf reports.tar.gz reports/" \
                        -b
            ansible "*" -i ${PWD}/$host_conf -m fetch -a "dest=$PWD src=${exe_path}/reports.tar.gz" \
                        -b
            mv ${e}/${exe_path}/reports.tar.gz . \
                && tar zxvf reports.tar.gz \
                && rm -f reports.tar.gz
            if [ -d $e ]; then
                rm -rf $e
            fi
            mkdir ${e}-Report && mv reports ${e}-Report/test-logs
        done

        # clear environ
        ansible "*" -i ${PWD}/$host_conf -m shell -a "rm -rf $exe_path" -b

        # save console output to log in each host
        for e in $(grep -E '^([0-9]{1,3}\.){3}[0-9]{1,3}$' $host_conf)
        do
            curl -s --location ${CI_JOB_URL}/raw > ${e}-Report/console.log
            sed -i -r 's/'$(echo -e "\033")'\[[0-9]{1,2}(;([0-9]{1,2})?)?[mK]|\r//g' ${e}-Report/console.log
        done
  tags:
    - IPT-K8S-NODE2
  only:
    - master
  allow_failure: true
  artifacts:
    name: ${CI_PROJECT_NAME}-Reports
    expire_in: 30d
    when: on_success
    paths:
      - ${PWD}/*.*.*.*-Report

cleanEnv:
  <<: *tool
  stage: cleanup
  script:
    - sh tool-gitlab-deployment/pipeline_clean.sh
  tags:
    - IPT-K8S-NODE2
  when: always
